### ISSUE TITLE
bug door 

### ISSUE THREAD

**Issue by bbussink** [GemeenteUtrecht/bereikbaarheid-frontend#29] opened 2024-05-28 17:06 UTC
**Describe the bug**
The code expects from  the RDW API a value with the name maximum_massa_samenstelling (which does not exist anymore, at least not in all cases)

**To Reproduce**
1. Go to  https://kaart.nationaalwegenbestand.nl/bereikbaarheid with license plate bxls14 and height 4 meter 
2. Click on go with checkboxes unchecked
![image](https://github.com/GemeenteUtrecht/bereikbaarheid-frontend/assets/96256875/165e64d2-a421-4b93-8c32-7acf6fcb708d)

**Expected behavior**
the page should show the RDW results but does not 

**Screenshots**
I believe the problem is the following.
on the left the code expects a column in the RDW data with the name 'maximum_massa_samenstelling'
this column does not exist in the API (anymore) so it seems.
It used to be there and return a value.
This is the url of the API of RDW  https://opendata.rdw.nl/api/id/m9d7-ebf2.json?kenteken=BXLS14 
![image](https://github.com/GemeenteUtrecht/bereikbaarheid-frontend/assets/96256875/67b276c2-2ef0-4aee-9f8b-93c86e122d54)

So the bug is i believe on this page https://github.com/GemeenteUtrecht/bereikbaarheid-frontend/blob/main/src/api/rdw/vehicle/index.ts 

**Additional context**
The relevance of this value, if I remember correctly, is to check whether or not the vehicle weight together with the weight of the load should be lower then maximum_massa_samenstelling . If this value does not exist the code breaks. As a quick fix the maximum value could be hard coded as 60000 kg. Later it can replaced in a better way.

Also on the RDW webpage https://ovi.rdw.nl/ the value is 0 (problaby not existing and then defaulting to 0 )
![image](https://github.com/GemeenteUtrecht/bereikbaarheid-frontend/assets/96256875/61485642-c98a-4fbe-bc16-9b89b1f15d56)

**Comment by sidneygijzen** [comment] 2024-05-29 12:06
Hi @bbussink 

Thank you for the detailed report. Unfortunately I cannot reproduce the issue. When I enter the provided license plate and vehicle height, the page shows the RDW results.

A possible explanation for the experienced issue could be that the RDW was fixing a data delta issue yesterday. Please see [this forum post](https://groups.google.com/g/voertuigen-open-data/c/JPz3VoIemUs/m/EmHYL1zCAQAJ) for more details.

Additionally, in the linked Amsterdam issue, you reported everything works as expected. So, I am closing this issue for now. Feel free to reopen if you have any additional questions.

**Closed by sidneygijzen** 2024-05-29 12:06 UTC
